remove unused var
../../../../../../kernel/samsung/gta4xl/drivers/lindroid-drm/evdi_fb.c:105:21: error: unused variable 'dev' [-Werror,-Wunused-variable]
  105 |         struct drm_device *dev = efb->base.dev;
      |                            ^~~
1 error generated.